apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      volumes:
      - name: tmp-volume
        emptyDir: {}
      serviceAccountName: default
      containers:
      - image: austinmundy90/numeric-app:latest
        name: devsecops-container
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000  # Use a higher UID
          # Remove or comment out readOnlyRootFilesystem for now
          # readOnlyRootFilesystem: true